- name: Get Current Job Log URL
  uses: Tiryoh/gha-jobid-action@v0
  id: jobs
  with:
    github_token: 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
    job_name: test
    per_page: 30
